default_config:

recorder:
    auto_purge: true
    purge_keep_days: 1
    commit_interval: 5
    include:
        domains:
            - input_boolean
            - input_number
            - input_select
            - switch
            - sensor
            - binary_sensor
            - number
            - select
            - zendure_local

logger:
    default: warning
    logs:
        custom_components.zendure_local: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
#     start: true
#     wait: false
#     port: 5678

# Input helpers to simulate Zendure device data for development
input_number:
    fake_battery_level:
        name: Battery Level
        min: 0
        max: 100
        step: 1
        icon: mdi:battery
        unit_of_measurement: "%"
        mode: box
    fake_solar_power:
        name: Solar Power
        min: 0
        max: 1000
        step: 10
        icon: mdi:solar-power
        unit_of_measurement: W
        mode: box
    fake_grid_power:
        name: Grid Power
        min: 0
        max: 1000
        step: 10
        icon: mdi:transmission-tower
        unit_of_measurement: W
        mode: box
    fake_output_power:
        name: Output Power
        min: 0
        max: 800
        step: 10
        icon: mdi:flash
        unit_of_measurement: W
        mode: box
    fake_temperature:
        name: Device Temperature
        min: 0
        max: 60
        step: 0.1
        icon: mdi:thermometer
        unit_of_measurement: °C
        mode: box

input_boolean:
    fake_zendure_online:
        name: Zendure Device Online
        icon: mdi:wifi
    fake_ac_status:
        name: AC Status
        icon: mdi:power-plug
    fake_dc_status:
        name: DC Status
        icon: mdi:power-plug-outline

# Note: The actual Zendure Local integration will be configured through the UI
# This file provides fake entities for testing and development purposes